name = "cloudflare-docker-proxy"
main = "src/index.js"
compatibility_date = "2023-12-01"
routes = [
  { pattern = "docker.tkbond.net", custom_domain = true },
]

[[r2_buckets]]
binding = "REGISTRY_BUCKET"
bucket_name = "myt"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "libcuda.so"

[env.dev.vars]
MODE = "debug"
CUSTOM_DOMAIN = "tkbond.net"

[[env.dev.r2_buckets]]
binding = "REGISTRY_BUCKET"
bucket_name = "myt"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.tkbond.net", custom_domain = true },
]

[[env.production.r2_buckets]]
binding = "REGISTRY_BUCKET"
bucket_name = "myt"

[env.production.vars]
MODE = "production"

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.libcuda.so", custom_domain = true }

[[env.staging.r2_buckets]]
binding = "REGISTRY_BUCKET"
bucket_name = "myt"

[env.staging.vars]
MODE = "staging"
